In [1]:
from keras.models import Model, load_model  

/home/eric/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# from mobilenet_v2 import relu6
# from mobilenet_v2 import DepthwiseConv2D
# model = load_model("./trained_model/mobilenet_v2/model_weights.25-0.7927.hdf5",custom_objects={'relu6': relu6,'DepthwiseConv2D':DepthwiseConv2D})
# model=load_model('./trained_model/inception_resnet_v2/model_weights.13-0.8069.hdf5')
model=load_model('./trained_model/xception/model_weights.12-0.7806.hdf5')
model.compile(loss='categorical_crossentropy',
        optimizer='rmsprop',
        metrics=['accuracy'])
print(model.summary())

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 111, 111, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
block1_conv1_bn (BatchNormaliza (None, 111, 111, 32) 128         block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_conv1_act (Activation)   (None, 111, 111, 32) 0        

In [52]:
from keras.preprocessing.image import ImageDataGenerator
train_data_dir = '/home/eric/data/ai_challenger_plant_train_20170904/AgriculturalDisease_trainingset/data'
train_datagen = ImageDataGenerator(1.0/255)
test_datagen = ImageDataGenerator(1.0/255)

classes=[]
with open("labels.txt","r") as f:
    for line in f.readlines():
        classes.append(line.strip("\n").split(" ")[0])

train_generator = train_datagen.flow_from_directory(
        train_data_dir,
        shuffle=True,
        target_size=(224, 224),
        batch_size=16,
        color_mode="rgb",
        classes=classes,
        class_mode='categorical',
        seed=42
        )
generator=test_datagen.flow_from_directory(
                         '/home/eric/data/ai_challenger_plant_train_20170904/AgriculturalDisease_testA',
                         target_size=(224,224),
                         batch_size=1,
                         class_mode=None,
                         shuffle=False,
                         seed=42
                    )


Found 32739 images belonging to 61 classes.
Found 4959 images belonging to 1 classes.


In [53]:
probability=model.predict_generator(generator,steps=10,verbose=1)

  15/4959 [..............................] - ETA: 1:37

/home/eric/anaconda3/lib/python3.6/site-packages/keras/preprocessing/image.py:536: UserWarning: This ImageDataGenerator specifies `featurewise_center`, but it hasn'tbeen fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '


4959/4959 [==============================] - 73s 15ms/step


In [54]:
generator.filenames[0]

'images/0003faa8-4b27-4c65-bf42-6d9e352ca1a5___RS_Late.B 4946.JPG'

In [55]:
probability[0]

array([1.0409849e-18, 1.4880719e-20, 2.2943496e-20, 4.7416914e-20,
       5.4397799e-27, 7.0553446e-29, 3.3491083e-23, 1.5501724e-22,
       3.1640229e-22, 4.9358747e-17, 1.2044122e-33, 4.1035304e-27,
       9.9700462e-19, 1.3971462e-13, 5.5351706e-19, 6.9455411e-13,
       9.5336007e-21, 6.7542454e-23, 8.1108211e-18, 1.6424932e-16,
       2.6704498e-14, 1.0844732e-12, 3.5556817e-23, 5.6032010e-17,
       3.0662275e-17, 2.1646214e-11, 4.6295221e-11, 3.6830805e-14,
       1.2632929e-17, 7.5677093e-17, 3.5109328e-16, 2.8070788e-19,
       1.1945256e-16, 3.5249474e-21, 8.5269324e-24, 1.7733318e-16,
       9.3708703e-15, 7.8289029e-09, 6.0033319e-26, 2.6546674e-28,
       4.9611379e-22, 3.9888552e-20, 8.7333196e-21, 4.4128018e-20,
       5.8845873e-27, 5.5517863e-21, 9.5282711e-18, 1.6229414e-10,
       3.2055215e-08, 1.0000000e+00, 5.1660423e-19, 7.9174435e-16,
       1.4203416e-25, 2.4541916e-21, 1.3424327e-22, 1.0046346e-14,
       5.3550624e-17, 1.8141313e-17, 5.2032803e-13, 1.7965225e

In [56]:
import numpy as np
sorted_arr=np.argsort(probability)
sorted_arr[0][-1]

49

In [57]:
generator.reset()
pred=model.predict_generator(generator,steps=2,verbose=1)
predicted_class_indices=np.argmax(pred,axis=1)

  15/4959 [..............................] - ETA: 1:36

/home/eric/anaconda3/lib/python3.6/site-packages/keras/preprocessing/image.py:536: UserWarning: This ImageDataGenerator specifies `featurewise_center`, but it hasn'tbeen fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '


4959/4959 [==============================] - 73s 15ms/step


In [58]:
predicted_class_indices[1000:1100]

array([45, 26, 47, 25, 47, 25, 40, 37, 28, 46, 32, 25, 34, 59, 23, 34, 25,
       52, 12, 31, 58, 45, 59, 26,  0, 25, 51, 44, 54, 35, 32, 32, 59, 26,
       55, 23, 19, 11, 40, 37, 35, 47, 41, 57, 35,  6, 19, 21, 55, 37, 16,
       26, 38,  3, 25, 59, 25, 56, 11, 16, 37, 58,  0, 52,  2, 25, 58,  0,
       47,  0,  1, 30, 35, 26, 25, 35, 30, 35, 26, 15, 28, 37, 53, 30, 43,
       33, 33, 41, 26, 20, 33, 25, 58, 12,  0, 23, 56, 59, 56, 29])

In [59]:
import pandas as pd
filenames=generator.filenames
result=pd.DataFrame({'FileName':filenames,
                    'Predictions':predicted_class_indices})
result.to_csv('results.csv',index=False)

In [60]:
from tqdm import tqdm
result = []
for i in tqdm(range(len(filenames))):
    temp_dict = {}
    temp_dict['image_id'] = filenames[i].split('/')[-1]
    temp_dict['disease_class'] = int(predicted_class_indices[i])
    result.append(temp_dict)
#     break
#     print('image %s is %d' % (test_image, sorted_arr[:,-1][0]))
import json
with open('submit.json', 'w') as f:
    json.dump(result, f)
    print('write result json, num is %d' % len(result)) 

100%|██████████| 4959/4959 [00:00<00:00, 703995.72it/s]

write result json, num is 4959


In [4]:
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img
import cv2, numpy as np
from keras.applications import imagenet_utils
preprocess = imagenet_utils.preprocess_input
# image_path = '/home/eric/data/ai_challenger_plant_train_20170904/AgriculturalDisease_validationset/data/1/43234193db4aefa1245592ab36d6c946.jpg'
image_path='/home/eric/data/ai_challenger_plant_train_20170904/AgriculturalDisease_trainingset/data/1/fac4a730a7721beb7403371b1e627277.jpg'
img_width, img_height = 224, 224
image = cv2.resize(cv2.imread(image_path), (img_width, img_height)).astype(np.float32)
# image = load_img(image_path, target_size=(img_width,img_height))
image /= 255.0
image = img_to_array(image)
image = np.expand_dims(image, axis=0)
# image=image/255.0
# image = preprocess(image)
predictions=model.predict(image)
image

array([[[[0.6117647 , 0.50980395, 0.5647059 ],
         [0.59607846, 0.49411765, 0.54901963],
         [0.58431375, 0.48235294, 0.53333336],
         ...,
         [0.6509804 , 0.5568628 , 0.59607846],
         [0.63529414, 0.5411765 , 0.5803922 ],
         [0.6156863 , 0.52156866, 0.56078434]],

        [[0.6117647 , 0.50980395, 0.5647059 ],
         [0.6117647 , 0.50980395, 0.5647059 ],
         [0.6156863 , 0.5137255 , 0.5686275 ],
         ...,
         [0.654902  , 0.56078434, 0.6       ],
         [0.6901961 , 0.59607846, 0.63529414],
         [0.7294118 , 0.63529414, 0.6745098 ]],

        [[0.6       , 0.5019608 , 0.5529412 ],
         [0.6       , 0.49803922, 0.5529412 ],
         [0.6       , 0.49803922, 0.5529412 ],
         ...,
         [0.61960787, 0.5254902 , 0.5647059 ],
         [0.6       , 0.5058824 , 0.54509807],
         [0.5921569 , 0.49803922, 0.5372549 ]],

        ...,

        [[0.627451  , 0.5372549 , 0.5921569 ],
         [0.63529414, 0.54509807, 0.6       ]

In [5]:
predictions

array([[2.63650800e-05, 6.03371357e-13, 1.20812709e-20, 1.86288873e-10,
        1.99314843e-21, 3.47929380e-28, 1.48060164e-04, 8.90452788e-15,
        5.04146641e-15, 2.97245549e-07, 1.13840323e-28, 2.17847560e-27,
        4.10611257e-02, 9.35056359e-02, 8.74694761e-12, 4.18123836e-03,
        3.79479825e-01, 1.20389727e-23, 3.44746428e-22, 1.18160296e-23,
        8.29511890e-08, 1.31631923e-08, 1.15668712e-29, 2.71920291e-28,
        3.41682266e-10, 3.31076592e-01, 1.12855975e-02, 1.78705249e-02,
        1.37580892e-05, 4.99541522e-04, 6.18043464e-11, 2.02263835e-12,
        8.01639571e-13, 1.30806398e-02, 1.53369454e-22, 1.19313218e-20,
        1.92652838e-12, 6.20452311e-13, 3.47465385e-19, 6.21299118e-24,
        7.47540972e-13, 5.50675607e-17, 1.20259459e-14, 8.09082218e-16,
        8.61733072e-17, 4.81308844e-26, 3.48433088e-11, 4.14584008e-16,
        1.95736112e-03, 2.47716140e-02, 1.56667799e-08, 3.11523946e-13,
        5.66839676e-17, 6.45449267e-27, 8.39499650e-12, 2.152805

In [6]:
sorted_arr=np.argsort(predictions)
sorted_arr[:,-1][0]

16

In [7]:
import os
test_dir='/home/eric/data/ai_challenger_plant_train_20170904/AgriculturalDisease_testA/images'
# test_dir='/home/eric/data/ai_challenger_plant_train_20170904/AgriculturalDisease_validationset/images'
test_images = os.listdir(test_dir)
test_images[0]

'5613dcbdddd99c41446bb728592b4068.jpg'

In [8]:
from tqdm import tqdm
result = []
for test_image in tqdm(test_images):
    temp_dict = {}
    img = cv2.resize(cv2.imread(os.path.join(test_dir,test_image)), (img_width, img_height)).astype(np.float32)
    img /= 255.0
    image = img_to_array(img)
    image = np.expand_dims(image, axis=0)
    predictions=model.predict(image)
    sorted_arr=np.argsort(predictions)
    temp_dict['image_id'] = test_image
    temp_dict['disease_class'] = int(sorted_arr[:,-1][0])
    result.append(temp_dict)
#     break
#     print('image %s is %d' % (test_image, sorted_arr[:,-1][0]))
    

100%|██████████| 4959/4959 [01:34<00:00, 52.38it/s]


In [9]:
import json
with open('submit.json', 'w') as f:
    json.dump(result, f)
    print('write result json, num is %d' % len(result))

write result json, num is 4959
